name: Tests CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installer les dépendances Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Installer les dépendances NPM
        run: npm install

      - name: Exécuter les tests Jest
        run: npm run test

      - name: Cypress run
        uses: cypress-io/github-action@v6