name: GitHub Actions Demo
run-name: Push application to docker hub and on server 🚀
on: [push]
jobs:
  Push-Application-To-Docker:
    runs-on: ubuntu-latest
    steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{ secrets.IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: Push-Application-To-Docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
          sudo apt-get install sshpass

      - name: Deploy to server
        run: |
          sshpass -p '${{ secrets.VM_PASSWORD }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.VM_SSH }} <<'ENDSSH'
          docker container stop ${{ secrets.CONTAINER_NAME }};
          docker container rm ${{ secrets.CONTAINER_NAME }};
          docker image rm ${{ secrets.IMAGE_NAME }};
          docker run -dit --rm --name ${{ secrets.CONTAINER_NAME }} -p 5001:5000 ${{ secrets.IMAGE_NAME }}
          ENDSSH
